export const getArticles = async () => {
  const res = await fetch(`http://localhost:8888/api/articles/`);
  let data = await res.json();
  return data;
};

export const checkForArticle = async (title) => {
  const res = await fetch(`http://localhost:8888/api/articles/`);
  const articles = await res.json();
  const foundArticle = articles.find((article) => {
    return article.title === title;
  });
  if (foundArticle) {
    return false;
  } else {
    return true;
  }
};

export  const fetchArticles = async (page) => {
  const res = await fetch("https://bloomberg-market-and-financial-news.p.rapidapi.com/news/list?id=markets", {
    "method": "GET",
    "headers": {
      "x-rapidapi-key": "26b171259cmshcab3cc72d758417p1c9e3ajsn5b654972df21",
      "x-rapidapi-host": "bloomberg-market-and-financial-news.p.rapidapi.com"
    }
  })

  // const res = await fetch(
  //   `http://newsapi.org/v2/everything?q=markets&language=en&sortBy=popularity&pageSize=6&page=${page}&apiKey=${process.env.REACT_APP_NEWS_API_KEY}`
  // );

  const data = await res.json();
  let modules = data.modules;
  modules = modules.filter((module) => module.stories.length > 0);
  console.log(modules);

  modules.map( (module) => {

        module.stories.map( async (story) => {
          let { title, autoGeneratedSummary, byline, internalID, published, thumbnailImage, shortURL } = story;
          const check = await checkForArticle(title);

          if (check) {
            const req = await fetch(`http://localhost:8888/api/articles/`, {
              method: "POST",
              body: JSON.stringify({
                title,
                content: autoGeneratedSummary,
                author: byline,
                publishedAt: published,
                url: shortURL,
                urlToImage: thumbnailImage,
              }),
              headers: {
                "Content-Type": "application/json",
              },
            });
          }
        })
      }
    );
  return "Articles added to db";

};

